version: "3.9"

services:

  web:

    build: .

    container_name: municipalconnect_web

    restart: always

    command: gunicorn municipalConnect.wsgi:application --bind 0.0.0.0:8000

    volumes:

      - .:/app

      - static_volume:/app/staticfiles

    depends_on:

      - db

    environment:

      - DEBUG=0

      - DATABASE_URL=postgres://postgres:postgres@db:5432/municipal_db


  db:

    image: postgres:16

    container_name: municipalconnect_db

    restart: always

    environment:

      POSTGRES_DB: municipal_db

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: postgres

    volumes:

      - postgres_data:/var/lib/postgresql/data/


  nginx:

    image: nginx:latest
    container_name: municipalconnect_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
  redis:
      image: redis:7
      container_name: municipalconnect_redis
      ports:
        - "6379:6379"

  celery:
      build: .
      command: celery -A municipalConnect worker -l info
      container_name: municipalconnect_celery
      depends_on:
        - redis
        - db
      env_file:
        - .env


volumes:

  postgres_data:
  static_volume: