# Generated by Django 6.0.2 on 2026-03-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0007_skill_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="skills", to="skills.skillcategory"
            ),
        ),
    ]
