# Generated by Django 6.0.2 on 2026-03-30 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("reports", "0006_alter_report_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reports.report",
            ),
        ),
    ]
